config/routes.rb
RainforestInclass::Application.routes.draw do

  resources :products do
    resources :reviews, :only => [:create]
  end

  resources :users, :only => ["new", "create"]

  resources :sessions, :only => ["new", "create"]
  delete "/sessions" => "sessions#destroy"

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price_in_cents

  validates :name, :presence => true
  validates :description, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}  

  has_many :reviews

  def formatted_price
    "$#{(self[:price_in_cents].to_f/100)}"
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  attr_accessible :comment

  validates :user, :presence => true
  validates :product, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :username
  has_secure_password
  validates_presence_of :password, :on => :create

  validates :email, {
    :uniqueness => true,
    :presence => true
  }

  validates :username, {
    :length => {:minimum => 3},
    :presence => true,
    :uniqueness => true
  }

  def username_string
    self[self[:username].present? ? :username : :email]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    @review = Review.new

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def index
    @products = Product.all

    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.json { head :no_content }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_path(@product.id) }
        format.json { render json: @product }
      else
        format.html do
          flash.now[:alert] = "Mistakes were made. Forms were mis-filled in. Move on."
          render :new
        end
        format.json { render json: @product.errors, status: :unprocessable_entity  }
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to product_path(@product.id) }
        format.json { render json: @product }
      else
        format.html do
          flash.now[:alert] = "Mistakes were made. Forms were mis-filled in. Move on."
          render :edit
        end
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include ApplicationHelper

  before_filter :verify_logged_in

  def create
    @product = Product.find params[:product_id]

    @review = @product.reviews.build(params[:review])
    @review.user_id = current_user.id

    if @review.save
      flash[:notice] = "Review added!"
      redirect_to product_path(@product.id)
    else
      flash.now[:alert] = "There was an error in your review. Stop haxoring our webs"
      render "products/show"
    end
  end

  protected

  def verify_logged_in
    if current_user.blank?
      flash[:alert] = "You must log in to add a review"
      redirect_to new_session_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # The login form
  def new
    @user = User.new
  end

  # Authenticating the login form post
  def create
    @user = User.where(:email => params[:user][:email]).first

    if @user.present? and @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      @user = User.new params[:user]
      flash.now[:alert] = "bad username or password"
      render :new, :status => 500
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to products_url
    # redirect_to products_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
      redirect_to products_path, :notice => "Signed Up!"
    else
      flash.now[:alert] = "There were some problems in your information"
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    return nil if session[:user_id].blank?
    @current_user ||= User.find session[:user_id]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RainforestInclass</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:alert].present? %>
  <div class="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:notice].present? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if current_user.present? %>
  Logged in as <%= current_user.email %>
  <%= link_to "Log out", sessions_path, :method => "DELETE" %>
<% else %>
  <%= link_to "Log in", new_session_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

  <% if @product.errors.present? %>
    <% @product.errors.full_messages.each do |error| %>
      <div class="alert">
        <%= error %>
      </div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :price_in_cents, "Price (cents):" %>
    <%= f.text_field :price_in_cents %>
  </p>

  <p>
    <div class="form-label">
      <%= f.label :description %>
    </div>
    <%= f.text_area :description %>
  </p>

  <%= f.submit %>

<% end %>

app/views/products/edit.html.erb
<h1> Edit Product </h1>

<%= render "form" %>

app/views/products/index.html.erb
<%= link_to "Add a product", new_product_path %>
<h1> Products </h1>

<% @products.each do |product| %>
  <%= link_to product_path(product.id) do %>
    <h2>
      <%= product.formatted_price %>
      <%= product[:name] %>
    </h2>
  <% end %>
  <p><%= truncate(product[:description], length: 100) %></p>
<% end %>

app/views/products/new.html.erb
<h1> Add a Product </h1>

<%= render "form" %>

app/views/products/show.html.erb
<h2>
  <%= @product.formatted_price %>
  <%= @product[:name] %>
</h2>

<%= link_to "Edit", edit_product_path(@product.id) %>

<p><%= @product[:description] %></p>

<%= form_for [@product, @review] do |f| %>

  <p>
    <h3> Add a review </h3>
    <%= f.text_area :comment %>
  </p>

  <%= f.submit %>

<% end %>

<h3> Reviews </h3>

<% @product.reviews.each do |review| %>
  <div class="review">
    <div class="poster">Posted by <%= review.user.username_string %> on <%= review.created_at %></div>
    <p class="comment">
    <%= review.comment %>
    </p>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.present? %>
    <% @user.errors.full_messages.each do |error| %>
      <div class="alert">
        <%= error %>
      </div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit %>

<% end %>